version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_support_gateway_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@postgres/ai_support_gateway_prod
      - SECRET_KEY_BASE=your_secret_key_base
      - GUARDIAN_SECRET_KEY=your_guardian_secret_key
      - PHX_HOST=localhost
    depends_on:
      - postgres

volumes:
  postgres_data: 